import { base44 } from '@/api/base44Client';
import { computeDivergence } from '@/lib/divergence';


/**
 * Generates and persists an artifact for a resolved incident.
 */
export async function generateAndPersistArtifact(incidentId) {
  try {
    const incidentResults = await base44.entities.Incident.filter({ id: incidentId });
    if (!incidentResults || incidentResults.length === 0) {
      console.warn(`Artifact generation: incident ${incidentId} not found`);
      return;
    }
    const incident = incidentResults[0];

    const events = await base44.entities.IncidentEvent.filter({ incident_id: incidentId });
    const sortedEvents = events.sort((a, b) => a.step_order - b.step_order);
    const firstEvent = sortedEvents[0];

    // Gap #11: divergence across the full sequence, not only step 1.
    const div = computeDivergence(sortedEvents);
    const diverged = div.diverged > 0;
    const suggested = firstEvent?.suggested_action || null;
    const actual = firstEvent?.message || null;

    let ttrMinutes = 0;
    if (incident.created_date && incident.resolved_at) {
      const createdTime = new Date(incident.created_date).getTime();
      const resolvedTime = new Date(incident.resolved_at).getTime();
      ttrMinutes = Math.round((resolvedTime - createdTime) / 60000);
    }

    const eventSequence = sortedEvents.map((e, idx) => {
      const perStep = div.perStep[idx] || {};
      return {
        step: idx + 1,
        message: e.message,
        suggested: perStep.suggested ?? null,
        diverged: !!perStep.diverged,
        timestamp: e.created_date || new Date().toISOString(),
      };
    });


    const markdown = generateMarkdownExport({
      service: incident.service,
      symptom: incident.symptom,
      outcome: incident.outcome,
      ttrMinutes,
      createdAt: incident.created_date,
      resolvedAt: incident.resolved_at,
      firstIntention: firstEvent?.message || 'Not captured',
      suggestionShown: firstEvent?.suggested_action || 'None',
      diverged,
      divergedCount: div.diverged,
      totalWithSuggestion: div.total,
      actualFirstAction: actual,
      suggestedAction: suggested,
      eventSequence,
      rootCauseNote: incident.root_cause_note || 'Not captured',
    });


    const existingArtifacts = await base44.entities.Artifact.filter({ incident_id: incidentId });

    const artifactData = {
      incident_id: incidentId,
      service: incident.service,
      symptom: incident.symptom,
      first_intention: firstEvent?.message || null,
      suggestion_shown: firstEvent?.suggested_action || null,
      actual_first_action: actual,
      diverged,
      event_sequence: eventSequence,
      outcome: incident.outcome,
      root_cause_note: incident.root_cause_note || null,
      ttr_minutes: ttrMinutes,
      markdown_export: markdown,
    };

    if (existingArtifacts && existingArtifacts.length > 0) {
      await base44.entities.Artifact.update(existingArtifacts[0].id, artifactData);
    } else {
      await base44.entities.Artifact.create(artifactData);
    }
  } catch (error) {
    console.error('Error generating artifact:', error);
    throw error;
  }
}

function generateMarkdownExport(data) {
  const divergenceHeadline =
    data.totalWithSuggestion > 0
      ? `Divergence: ${data.divergedCount}/${data.totalWithSuggestion} steps`
      : 'Divergence: no suggestions recorded';
  const divergenceSection = data.diverged
    ? `${divergenceHeadline}\n\nFirst divergent step — Suggested: ${data.suggestedAction}\nActual: ${data.actualFirstAction}`
    : `${divergenceHeadline}\n\nNo divergence — actions matched suggestions.`;

  const eventLines = data.eventSequence
    .map(e => `**[${e.step}]** ${e.message}${e.diverged ? '  _(diverged)_' : ''}  \`${e.timestamp}\``)
    .join('\n');


  return `# TraceCrumb Incident Report

**Service:** ${data.service}
**Symptom:** ${data.symptom}
**Outcome:** ${data.outcome.toUpperCase()} | **TTR:** ${data.ttrMinutes} min
**Opened:** ${data.createdAt} | **Closed:** ${data.resolvedAt}

## First Intention

${data.firstIntention}

## Suggestion Shown

${data.suggestionShown}

## Divergence

${divergenceSection}

## Diagnostic Sequence

${eventLines}

## Root Cause

${data.rootCauseNote}

---

*Generated by TraceCrumb*`;
}
